---
- name: install requirements and test requirements with pipenv
  environment:
    LC_ALL: "C.UTF-8"
    LANG: "en_GB.UTF-8"
  command: "pipenv --bare install --dev"
  args:
    chdir: "{{ site_folder }}"